server:
  host: "localhost"
  port: 50051

gcp:
  project_id: "cactus-v1"
  location: "us-central1"
  weight_bucket: "weights"
  key_file: "cactus-gcp-credentials.json"
  jwt_secret_name: "projects/263237337139/secrets/TangoJWTSecret/versions/latest"
  test_token_secret_name: "projects/263237337139/secrets/TangoTestTokens/versions/1"

task:
  timeout_seconds: 1
  reaper_interval_milliseconds: 500

logging:
  level: "INFO"
  file: "server.log"
