server:
  name: tango
  host: "localhost"
  port: 50051

gcp:
  project_id: "tango-v1"
  location: "us-central1"
  weight_bucket: "tango-llm-weights"
  records_bucket: "tango-records"
  key_file: "gcp-credentials.json"
  jwt_secret_name: <insert-jwt-secret-name>
  test_token_secret_name: <insert-test-token-secret-name>
  server_crt: <insert-server-crt>
  server_key: <insert-server-key>

task:
  timeout_seconds: 2
  reaper_interval_milliseconds: 2000 

logging:
  level: "INFO"
  file: "server.log"
