server:
  name: tango
  host: "localhost"
  port: 50051

gcp:
  project_id: "cactus-v1"
  location: "us-central1"
  weight_bucket: "cactus-llm-weights"
  records_bucket: "tango-records"
  key_file: "cactus-gcp-credentials.json"
  jwt_secret_name: "projects/263237337139/secrets/TangoJWTSecret/versions/latest"
  test_token_secret_name: "projects/263237337139/secrets/TangoTestTokens/versions/1"
  server_crt: "projects/263237337139/secrets/TangoTLSCert/versions/latest"
  server_key: "projects/263237337139/secrets/TangoTLSKey/versions/latest"

task:
  timeout_seconds: 2
  reaper_interval_milliseconds: 2000 

logging:
  level: "INFO"
  file: "server.log"
