server:
  host: "localhost"
  port: 50051

tokens:
  testToken: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3NDA5NDcyMzgsImlzc3VlciI6IkNhY3R1cyBFZGdlIn0.bfq0u8921So9E9ra8Qdh6nGph0XaRCyMHZaDEDn3cu8" 

task:
  timeout_seconds: 1
  reaper_interval_milliseconds: 500

logging:
  level: "INFO"
  file: "server.log"
