# --------------------------------------------
# Dockerfile for the Tango device client.
# It compiles the device simulator Go application using golang:1.20 and runs it on an Alpine base image.
# --------------------------------------------

FROM golang:1.20 AS builder
WORKDIR /app

COPY . .

RUN go build -v -o device_client ./test/device_client.go

FROM alpine:latest
RUN apk --no-cache add ca-certificates
WORKDIR /root/
COPY --from=builder /app/device_client .

CMD ["./device_client"]
