# --------------------------------------------
# Dockerfile for the Tango device client.
# It compiles the device simulator Go application using golang:1.20 and runs it on an Alpine base image.
# --------------------------------------------

FROM golang:1.20 AS builder
WORKDIR /app

COPY . .

RUN go build -o device_client ./device_client.go

FROM alpine:latest
WORKDIR /root/
COPY --from=builder /app/device_client .

EXPOSE 8080
CMD ["./device_client"]
