# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import protobuff_pb2 as protobuff__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in protobuff_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TangoServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SubmitTask = channel.unary_unary(
                '/protobuff.TangoService/SubmitTask',
                request_serializer=protobuff__pb2.TaskRequest.SerializeToString,
                response_deserializer=protobuff__pb2.TaskResponse.FromString,
                _registered_method=True)
        self.FetchTask = channel.unary_unary(
                '/protobuff.TangoService/FetchTask',
                request_serializer=protobuff__pb2.DeviceRequest.SerializeToString,
                response_deserializer=protobuff__pb2.TaskAssignment.FromString,
                _registered_method=True)
        self.ReportResult = channel.unary_unary(
                '/protobuff.TangoService/ReportResult',
                request_serializer=protobuff__pb2.TaskResult.SerializeToString,
                response_deserializer=protobuff__pb2.ResultResponse.FromString,
                _registered_method=True)
        self.GetJobStatus = channel.unary_unary(
                '/protobuff.TangoService/GetJobStatus',
                request_serializer=protobuff__pb2.JobStatusRequest.SerializeToString,
                response_deserializer=protobuff__pb2.JobStatusReply.FromString,
                _registered_method=True)


class TangoServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SubmitTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FetchTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportResult(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetJobStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TangoServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SubmitTask': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitTask,
                    request_deserializer=protobuff__pb2.TaskRequest.FromString,
                    response_serializer=protobuff__pb2.TaskResponse.SerializeToString,
            ),
            'FetchTask': grpc.unary_unary_rpc_method_handler(
                    servicer.FetchTask,
                    request_deserializer=protobuff__pb2.DeviceRequest.FromString,
                    response_serializer=protobuff__pb2.TaskAssignment.SerializeToString,
            ),
            'ReportResult': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportResult,
                    request_deserializer=protobuff__pb2.TaskResult.FromString,
                    response_serializer=protobuff__pb2.ResultResponse.SerializeToString,
            ),
            'GetJobStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetJobStatus,
                    request_deserializer=protobuff__pb2.JobStatusRequest.FromString,
                    response_serializer=protobuff__pb2.JobStatusReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'protobuff.TangoService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('protobuff.TangoService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TangoService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SubmitTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/protobuff.TangoService/SubmitTask',
            protobuff__pb2.TaskRequest.SerializeToString,
            protobuff__pb2.TaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FetchTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/protobuff.TangoService/FetchTask',
            protobuff__pb2.DeviceRequest.SerializeToString,
            protobuff__pb2.TaskAssignment.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReportResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/protobuff.TangoService/ReportResult',
            protobuff__pb2.TaskResult.SerializeToString,
            protobuff__pb2.ResultResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetJobStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/protobuff.TangoService/GetJobStatus',
            protobuff__pb2.JobStatusRequest.SerializeToString,
            protobuff__pb2.JobStatusReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
